server:
  port: 8999

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: UserManagement
          uri: lb://UserManagement  #
          predicates:
            - Path=/users/me/**,/auth/**

        - id: swag
          uri: lb://swag  #
          predicates:
            - Path=/home/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka